name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies and build
      run: |
        npm ci
        npm run build

    - name: Clone Azure Web App repository
      env:
        AZURE_USER: ${{ secrets.AZURE_USER }}
        AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
      run: |
        git clone https://$AZURE_USER:$AZURE_PASSWORD@webapp-healix-prod.scm.azurewebsites.net:443/webapp-healix-prod.git

    - name: Copy files to Azure repo
      run: |
        cp -r dist/* webapp-healix-prod/
        cp -r node_modules/ webapp-healix-prod/
        cp package.json webapp-healix-prod/

    - name: Commit and push changes
      run: |
        cd webapp-healix-prod
        git add -q *
        git commit -m "deploy"
        git push origin master
