name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone Azure Web App repository
      env:
        AZURE_USER: ${{ secrets.AZURE_USER }}
        AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
      run: |
        cd ..
        ls -al
        git clone https://$AZURE_USER:$AZURE_PASSWORD@webapp-healix-prod.scm.azurewebsites.net:443/webapp-healix-prod.git
        rm -rf webapp-healix-prod/*

    - name: Copy files to Azure repo
      run: |
        mv healix-backend/* webapp-healix-prod

    - name: Commit and push changes
      run: |
        cd webapp-healix-prod
        git config --global user.email "5252bb@daum.net"
        git config --global user.name "Ballbot"
        git add .
        DATE=$(date +'%Y-%m-%d')
        git commit -m "deploy on $DATE"
        git push origin master
